#include "lstatus.hpp"

char __lstatus_msg[LSTATUS_MAX_MSG_LEN + 1] = {0};

const char *__lstatus_str_repr[] =
{
    "LSTATUS_OK",
    "LSTATUS_BAD_ALLOC",
    "LSTATUS_FILE_IO_ERR",
    "LSTATUS_LIST_EMPTY",
    "LSTATUS_LIST_FULL",
    "LSTATUS_LIST_INVALID",
    "LSTATUS_LIST_NULL_ITER",
    "LSTATUS_LIST_BAD_ADDRESS",
    "LSTATUS_POOL_INVALID",
    "LSTATUS_LEXER_FAIL",
    "LSTATUS_PARSER_FAIL",
    "LSTATUS_BAD_AST",
    "LSTATUS_NOT_FOUND",
    "LSTATUS_ALREADY_PRESENT",
    "LSTATUS_CODE_GEN_FAIL",
    "LSTATUS_SYM_RESOLVE_ERR"
};