typedef enum
{
    OPCODE_NOP,
    OPCODE_PUSH_IMM,
    OPCODE_PUSH_RAX,
    OPCODE_PUSH_RBX,
    OPCODE_PUSH_RCX,
    OPCODE_PUSH_RDX,
    OPCODE_POP_RAX,
    OPCODE_POP_RBX,
    OPCODE_POP_RCX,
    OPCODE_POP_RDX,
    OPCODE_IN,
    OPCODE_OUT,
    OPCODE_ADD,
    OPCODE_SUB,
    OPCODE_MUL,
    OPCODE_DIV,
    OPCODE_HLT
} __opcodes;
